# Generated by Django 5.1 on 2024-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='image',
            field=models.ImageField(blank=True, default='noImage.png', upload_to=''),
        ),
    ]
