# Generated by Django 5.1 on 2024-08-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_locations_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='locations',
            name='capacity',
            field=models.IntegerField(null=True, verbose_name='定員'),
        ),
        migrations.AddField(
            model_name='locations',
            name='created_date',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='locations',
            name='phonenumber',
            field=models.CharField(max_length=11, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='locations',
            name='postal_code',
            field=models.CharField(max_length=7, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='locations',
            name='price_high',
            field=models.IntegerField(null=True, verbose_name='上限金額'),
        ),
        migrations.AddField(
            model_name='locations',
            name='price_low',
            field=models.IntegerField(null=True, verbose_name='下限金額'),
        ),
        migrations.AddField(
            model_name='locations',
            name='time_close',
            field=models.TimeField(null=True, verbose_name='閉店時間'),
        ),
        migrations.AddField(
            model_name='locations',
            name='time_open',
            field=models.TimeField(null=True, verbose_name='開店時間'),
        ),
        migrations.AddField(
            model_name='locations',
            name='updated_date',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=20, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelog.categories', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='image',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=50, verbose_name='店名'),
        ),
    ]
