# Generated by Django 5.1 on 2024-09-07 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_remove_reservation_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default='3', verbose_name='評価'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('location', 'customer')},
        ),
    ]
