# Generated by Django 5.1 on 2024-08-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0003_locations_address_locations_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='休日名')),
                ('created_date', models.TimeField(auto_now_add=True)),
                ('updated_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='created_date',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='updated_date',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='holiday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelog.holidays', verbose_name='店休日'),
        ),
    ]
