# Generated by Django 5.1 on 2024-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0004_holidays_categories_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
