# Generated by Django 5.1 on 2024-08-25 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0005_alter_locations_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('furigana', models.CharField(max_length=100, verbose_name='フリガナ')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
                ('membership_flg', models.BooleanField(default=False, verbose_name='有料会員フラグ')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='locations',
            name='category',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='holiday',
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=50, verbose_name='店舗名'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelog.customers', verbose_name='ユーザー名')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelog.locations', verbose_name='店舗名')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='予約日時')),
                ('headcount', models.IntegerField(verbose_name='予約人数')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelog.customers', verbose_name='予約者名')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelog.locations', verbose_name='店舗名')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='評価')),
                ('comment', models.TextField(null=True, verbose_name='コメント')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelog.customers', verbose_name='ユーザー名')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelog.locations', verbose_name='店舗名')),
            ],
        ),
        migrations.AddField(
            model_name='locations',
            name='category',
            field=models.ManyToManyField(to='tabelog.categories', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='locations',
            name='holiday',
            field=models.ManyToManyField(to='tabelog.holidays', verbose_name='店休日'),
        ),
    ]
