# Generated by Django 5.1 on 2024-11-02 14:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0006_stripe_customer_stripepaymentmethodid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='noImage.png', max_length=255, verbose_name='画像'),
        ),
    ]
