# Generated by Django 5.1 on 2024-08-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0006_admin_users_customers_remove_locations_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_users',
            new_name='Admin_user',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.RenameModel(
            old_name='Holidays',
            new_name='Holiday',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
