# Generated by Django 5.1 on 2024-08-25 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0007_rename_admin_users_admin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.RemoveField(
            model_name='location',
            name='holiday',
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelog.category', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='location',
            name='holiday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelog.holiday', verbose_name='店休日'),
        ),
    ]
