# Generated by Django 5.1 on 2024-08-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0008_remove_location_category_remove_location_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
